title = "Let's Encrypt"
contentDir = "content/da"
languageName = "Dansk"
languageCode = "da"
beforeColon = ""
weight = 190
description = """
  Let's Encrypt er en gratis, automatisk og åben certifikat 
 udsteeder bragt til dig af nonprofit organisationen <a href="https://www.abetterinternet.org/">Internet Security Research Group (ISRG)</a>. 
"""
paypalDonateImage = "https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif"
paypalCountry = "DK"
numberFormat = "-|.|."
viewInThatLanguage = "Se på Dansk"