title = "Let's Encrypt - Certificats SSL/TLS gratuits"
languageName = "Français"
contentDir = "content/fr"
languageCode = "fr-FR"
weight = 300
[params]
beforeColon = "&nbsp;"
description = """
  Let's Encrypt est une autorité de certification gratuite, automatisée et ouverte
  mise à votre disposition par la société d'utilité publique <a href="https://www.abetterinternet.org/">Internet Security Research Group (ISRG)</a>.
"""
paypalDonateImage = "https://www.paypalobjects.com/fr_FR/FR/i/btn/btn_donateCC_LG.gif"
paypalCountry = "FR"
numberFormat = "-|,| "
viewInThatLanguage = "Voir en Français"
