title = "Let's Encrypt"
contentDir = "content/pl"
languageName = "Polish"
languageCode = "pl"
weight = 475

[params]
beforeColon = ""
description = """
Let's Encrypt to bezpłatny, zautomatyzowany i otwarty urząd certyfikacji udostępniany przez organizację non-profit <a href="https://www.abetterinternet.org/">Internet Security Research Group (ISRG)</a>. Przeczytaj wszystkie tegoroczne informacje o nas w naszym <a href="https://www.abetterinternet.org/annual-reports/"> 2025 Rocznym Sprawozdaniu</a>.
"""
paypalDonateImage = "https://www.paypalobjects.com/pl_PL/i/btn/btn_donateCC_LG.gif"
paypalCountry = "PL"
numberFormat = "-|.|,"
viewInThatLanguage = "Pokaż w języku polskim"
