title = "Let's Encrypt - フリーな SSL/TLS 証明書"
contentDir = "content/ja"
languageName = "日本語"
languageCode = "ja"
weight = 400
[params]
beforeColon = ""
description = """
  Let's Encryptは、非営利団体の <a href="https://www.abetterinternet.org/">Internet Security Research Group (ISRG)</a> が提供する自動化されたフリーでオープンな認証局です。
"""
paypalDonateImage = "https://www.paypalobjects.com/ja_JP/JP/i/btn/btn_donateCC_LG.gif"
paypalCountry = "US"
numberFormat = "-|.|,"
viewInThatLanguage = "日本語で表示する"
