[en]
title = "Let's Encrypt - Free SSL/TLS Certificates"
contentDir = "content/en"
languageName = "English"
languageCode = "en-US"
#if colon ":" must be prefixed with a space : "&nbsp;" (example in [fr])
beforeColon = ""
# Weight used for sorting. (alphabetical order using languageCode, with English first)
weight = 10
description = """
  Let's Encrypt is a free, automated, and open certificate
  authority brought to you by the nonprofit <a href="https://www.abetterinternet.org/">Internet Security Research Group (ISRG)</a>.
"""
# PayPal image url from https://www.paypal.com/donate/buttons/unhosted
paypalDonateImage = "https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif"
# A country where PayPal has support for the language must be chosen. Click a Donate button and modify the GET parameters "country.x" and "locale.x" to find what is supported.
paypalCountry = "US"

[de]
title = "Let's Encrypt - Freie SSL/TLS Zertifikate"
contentDir = "content/de"
languageName = "Deutsch"
languageCode = "de-DE"
beforeColon = ""
weight = 20
description = """
  Let's Encrypt ist eine freie, automatisierte und offene Zertifizierungsstelle,
  herausgebracht für Sie durch <a href="https://www.abetterinternet.org/">Internet Security Research Group (ISRG)</a>.
"""
paypalDonateImage = "https://www.paypalobjects.com/de_DE/DE/i/btn/btn_donateCC_LG.gif"
paypalCountry = "DE"

[es]
title = "Let's Encrypt - Certificados SSL/TLS Gratuitos"
contentDir = "content/es"
languageName = "Español"
languageCode = "es-US"
beforeColon = "&nbsp;"
weight = 30
description = """
  Let's Encrypt es una autoridad de certificación gratuita, automatizada, y abierta traida a ustedes por la organización sin ánimos de lucro <a href="https://www.abetterinternet.org/">Internet Security Research Group (ISRG)</a>.
"""
paypalDonateImage = "https://www.paypalobjects.com/es_XC/i/btn/btn_donateCC_LG.gif"
paypalCountry = "ES"

[fr]
title = "Let's Encrypt - Certificats SSL/TLS gratuits"
languageName = "Français"
contentDir = "content/fr"
languageCode = "fr-FR"
beforeColon = "&nbsp;"
weight = 40
description = """
  Let's Encrypt est une autorité de certification gratuite, automatisée et ouverte
  apporté par l'<a href="https://www.abetterinternet.org/">Internet Security Research Group (ISRG)</a>, organisme à but non lucratif.
"""
paypalDonateImage = "https://www.paypalobjects.com/fr_FR/FR/i/btn/btn_donateCC_LG.gif"
paypalCountry = "FR"

[id]
title = "Let's Encrypt - Sertifikat SSL/TLS Gratis"
contentDir = "content/id"
languageName = "Bahasa Indonesia"
languageCode = "id-ID"
beforeColon = ""
weight = 50
description = """
  Let's Encrypt adalah otoritas sertifikasi terbuka yang gratis dan terotomatisasi,
  dipersembahkan oleh organisasi non-profit <a href="https://www.abetterinternet.org/">Internet Security Research Group (ISRG)</a>.
"""
paypalDonateImage = "https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif"
paypalCountry = "US"

[ja]
title = "Let's Encrypt - フリーな SSL/TLS 証明書"
contentDir = "content/ja"
languageName = "日本語"
languageCode = "ja"
beforeColon = ""
weight = 60
description = """
  Let's Encrypt is a free, automated, and open certificate
  authority brought to you by the non-profit <a href="https://www.abetterinternet.org/">Internet Security Research Group (ISRG)</a>.
"""
paypalDonateImage = "https://www.paypalobjects.com/ja_JP/JP/i/btn/btn_donateCC_LG.gif"
paypalCountry = "US"

[ko]
title = "Let's Encrypt - 무료 SSL/TLS 인증서"
contentDir = "content/ko"
languageName = "한국어"
languageCode = "ko-KR"
beforeColon = ""
weight = 70
description = """
  Let's Encrypt는 <a href="https://www.abetterinternet.org/"> 비영리 인터넷 보안 연구 그룹 (ISRG)</a>에서 가져온 무료, 자동 및 공개 인증 기관입니다.
"""
paypalDonateImage = "https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif"
paypalCountry = "US"

[pt-br]
title = "Let's Encrypt - Certificados SSL/TLS Gratuitos"
contentDir = "content/pt-br"
languageName = "Português do Brasil"
languageCode = "pt-BR"
beforeColon = ""
weight = 80
description = """
  Let's Encrypt é uma autoridade certificadora gratuita, automatizada e aberta
  que se tornou possível graças à organização sem fins lucrativos <a href="https://www.abetterinternet.org/">Internet Security Research Group (ISRG)</a>
"""
paypalDonateImage = "https://www.paypalobjects.com/pt_BR/BR/i/btn/btn_donateCC_LG.gif"
paypalCountry = "BR"

[ru]
title = "Let's Encrypt - Free SSL/TLS Certificates"
contentDir = "content/ru"
languageName = "Русский"
languageCode = "ru-RU"
beforeColon = ""
weight = 90
description = """
  Let's Encrypt - это бесплатный, автоматизированный и открытый Центр Сертификации, созданный для вас
  некоммерческой организацией <a href="https://www.abetterinternet.org/">Internet Security Research Group (ISRG)</a>.
"""
paypalDonateImage = "https://www.paypalobjects.com/ru_RU/RU/i/btn/btn_donateCC_LG.gif"
paypalCountry = "US"

[sr]
title = "Let's Encrypt - Besplatni SSL/TLS Sertifikati"
contentDir = "content/sr"
languageName = "Srpski"
languageCode = "sr"
beforeColon = ""
weight = 95
description = """
  Let's Encrypt je besplatno, automatizovano, i otvoreno sertifikaciono
  telo omogućeno od strane ne profitne <a href="https://www.abetterinternet.org/">Internet Security Research Group (ISRG)</a> grupe.
"""
paypalDonateImage = "https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif"
paypalCountry = "SP"

[sv]
title = "Let's Encrypt - Gratis SSL/TLS-certifikat"
contentDir = "content/sv"
languageName = "Svenska"
languageCode = "sv"
beforeColon = ""
weight = 97
description = """
  Let's Encrypt är en gratis, automatiserad och öppen certifikatutgivare
  skapad av icke-vinstdrivande <a href="https://www.abetterinternet.org/">Internet Security Research Group (ISRG)</a>.
"""
paypalDonateImage = "https://www.paypalobjects.com/sv_SE/SE/i/btn/btn_donateCC_LG.gif"
paypalCountry = "SE"

[zh-cn]
title = "Let's Encrypt - 免费的SSL/TLS证书"
contentDir = "content/zh-cn"
languageName = "简体中文"
languageCode = "zh-Hans-CN"
beforeColon = ""
weight = 100
description = """
  Let's Encrypt 是免费、开放和自动化的证书颁发机构。由非盈利组织<a href="https://www.abetterinternet.org/"
  style="white-space:nowrap;">互联网安全研究小组（ISRG）</a>运营。
"""
paypalDonateImage = "https://www.paypalobjects.com/zh_XC/i/btn/btn_donateCC_LG.gif"
paypalCountry = "US"

[zh-tw]
title = "Let's Encrypt - 免費的 SSL/TLS 憑證"
languageName = "繁體中文"
contentDir = "content/zh-tw"
languageCode = "zh-Hant-TW"
beforeColon = ""
weight = 110
description = """  
  Let's Encrypt 是免費、自動化和開放的憑證頒發機構，由非營利組織<a href="https://www.abetterinternet.org/">網路安全研究小組 (Internet Security Research Group, ISRG)</a> 營運。
  """
paypalDonateImage = "https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif"
paypalCountry = "US"
