title = "Let's Encrypt"
contentDir = "content/ru"
languageName = "Русский"
languageCode = "ru-RU"
beforeColon = ""
weight = 550
description = """
  Let's Encrypt - это бесплатный, автоматизированный и открытый Центр Сертификации, созданный для вас
  некоммерческой организацией <a href="https://www.abetterinternet.org/">Internet Security Research Group (ISRG)</a>.
"""
paypalDonateImage = "https://www.paypalobjects.com/ru_RU/RU/i/btn/btn_donateCC_LG.gif"
paypalCountry = "US"
numberFormat = "-|.|,"
viewInThatLanguage = "Просмотреть на русском"
