title = "Let's Encrypt"
contentDir = "content/hu"
languageName = "Magyar"
languageCode = "hu"
weight = 330

[params]
beforeColon = ""
description = """
A Let’s Encrypt egy ingyenes, automatizált és nyílt hitelesítésszolgáltató (Certificate Authority), amelyet a nonprofit <a href="https://www.abetterinternet.org/">Internet Security Research Group (ISRG)</a> működtet. Tudj meg többet idei nonprofit tevékenységünkről a <a href="https://www.abetterinternet.org/annual-reports/">2025-ös éves jelentésünkben</a>.
"""
paypalDonateImage = "https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif"
paypalCountry = "US"
numberFormat = "-|,| "
viewInThatLanguage = "Megtekintés magyar nyelven"
