[[main]]
name = "Ottenere Aiuto"
weight = 20
url = "https://community.letsencrypt.org/"
[[main]]
name = "Donare"
weight = 30
identifier = "donate"
[[main]]
name = "Chi Siamo"
weight = 40
identifier = "about"
[[main]]
name = "Internet Security Research Group (ISRG)"
weight = 20
identifier = "isrg"
parent = "about"
url = "https://www.abetterinternet.org/about/"
[[main]]
name = "Stato del Servizio"
weight = 60
identifier = "status"
parent = "about"
url = "https://letsencrypt.status.io/"
[[main]]
name = "Carriere"
weight = 80
identifier = "careers"
parent = "about"
url = "https://www.abetterinternet.org/careers/"
