[[main]]
name = "Trợ Giúp"
weight = 20
url = "https://community.letsencrypt.org/"
[[main]]
name = "Quyên Góp"
weight = 30
identifier = "donate"
[[main]]
name = "Giới Thiệu"
weight = 40
identifier = "about"
[[main]]
name = "Internet Security Research Group (ISRG)"
weight = 20
identifier = "isrg"
parent = "about"
url = "https://www.abetterinternet.org/about/"
[[main]]
name = "Tình Trạng Dịch Vụ"
weight = 60
identifier = "status"
parent = "about"
url = "https://letsencrypt.status.io/"
[[main]]
name = "Nghề Nghiệp"
weight = 80
identifier = "careers"
parent = "about"
url = "https://www.abetterinternet.org/careers/"
