[[main]]
name = "Uzyskaj pomoc"
weight = 20
url = "https://community.letsencrypt.org/"

[[main]]
name = "Blog"
weight = 25
url = "/blog/"

[[main]]
name = "Wesprzyj nas"
weight = 30
identifier = "donate"

[[main]]
name = "Zostań sponsorem"
weight = 40
identifier = "become-a-sponsor"
parent = "donate"
url = "https://www.abetterinternet.org/sponsor/"

[[main]]
name = "Obecni Sponsorzy i Fundatorzy"
weight = 40
identifier = "sponsors"
parent = "donate"
url = "https://www.abetterinternet.org/sponsors/"

[[main]]
name = "O Nas"
weight = 40
identifier = "about"

[[main]]
name = "Internet Security Research Group (ISRG)"
weight = 200
identifier = "isrg"
parent = "about"
url = "https://www.abetterinternet.org/about/"

[[main]]
name = "Status usługi"
weight = 60
identifier = "status"
parent = "about"
url = "https://letsencrypt.status.io/"

[[main]]
name = "Kariera"
weight = 110
identifier = "careers"
parent = "about"
url = "https://www.abetterinternet.org/careers/"

[[main]]
name = "Raporty roczne"
weight = 140
identifier = "annual-reports"
parent = "about"
url = "https://www.abetterinternet.org/annual-reports/"
