[[main]]
name = "PomoÄ‡"
weight = 20
url = "https://community.letsencrypt.org/"
[[main]]
name = "Doniraj"
weight = 30
identifier = "donate"
url = "/sr/donate/"
[[main]]
name = "O nama"
weight = 40
identifier = "about"
url = "/sr/about/"
[[main]]
name = "Internet Security Research Group (ISRG)"
weight = 20
identifier = "isrg"
parent = "about"
url = "https://www.abetterinternet.org/about/"
[[main]]
name = "Status Servisa"
weight = 60
identifier = "status"
parent = "about"
url = "https://letsencrypt.status.io/"
[[main]]
name = "Karijera"
weight = 80
identifier = "careers"
parent = "about"
url = "https://www.abetterinternet.org/careers/"
