[[main]]
name = "Obtenir de l'aide"
weight = 20
url = "https://community.letsencrypt.org/c/help/aide-en-francais"
[[main]]
name = "Faire un don"
weight = 30
identifier = "donate"
[[main]]
name = "À propos de nous"
weight = 40
identifier = "about"
[[main]]
name = "Internet Security Research Group (ISRG)"
weight = 20
identifier = "isrg"
parent = "about"
url = "https://www.abetterinternet.org/about/"
[[main]]
name = "État du service"
weight = 60
identifier = "status"
parent = "about"
url = "https://letsencrypt.status.io/"
[[main]]
name = "Emplois"
weight = 80
identifier = "careers"
parent = "about"
url = "https://www.abetterinternet.org/careers/"
