[[main]]
name = "Consigue Ayuda"
weight = 20
url = "https://community.letsencrypt.org/c/help/ayuda-en-espanol/22"
[[main]]
name = "Donar"
weight = 30
identifier = "donate"
url = "/es/donate/"
[[main]]
name = "Acerca De"
weight = 40
identifier = "about"
url = "/es/about/"
[[main]]
name = "Internet Security Research Group (ISRG)"
weight = 20
identifier = "isrg"
parent = "about"
url = "https://www.abetterinternet.org/about/"
[[main]]
name = "Status de Servicio"
weight = 60
identifier = "status"
parent = "about"
url = "https://letsencrypt.status.io/"
[[main]]
name = "Trabajos"
weight = 80
identifier = "careers"
parent = "about"
url = "https://www.abetterinternet.org/careers/"
