baseURL = "https://letsencrypt.org/"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

disableKinds = ["taxonomy", "taxonomyTerm"]

enableRobotsTXT = true

# Note that this currently has no effect in Hugo.
timezone = "America/Los_Angeles"


[params]

# Default page top graphic if not set in page front matter. This is an integer representing the base filename.
# See the JPEG files below /static/images.
top_graphic = 5

github_username = "letsencrypt"
twitter_username = "letsencrypt"
crowdfunding_url = "https://www.generosity.com/community-fundraising/make-a-more-secure-web-with-let-s-encrypt"

# Date and time formatting, see https://gohugo.io/functions/format/
time_format_RFC3339 = "2006-01-02T15:04:05Z07:00"
time_format_RFC822 = "Mon, 02 Jan 2006 15:04:05 -0700"
time_format_default = "Jan 2, 2006"

# Useful when translating.
enableMissingTranslationPlaceholders = true

[languages]
[languages.en]
title = "Let's Encrypt - Free SSL/TLS Certificates"
contentDir = "content/en"
languageName ="English"
languageCode= "en-us"
# Weight used for sorting.
weight = 10
description = """
  Let&rsquo;s&nbsp;Encrypt is a free, automated, and open certificate
  authority brought to you by the non-profit <a href="https://www.abetterinternet.org/">Internet Security Research Group (ISRG)</a>.
"""
[[languages.en.menu.main]]
 name = "Get Help"
 weight = 20
 url = "https://community.letsencrypt.org/"
 [[languages.en.menu.main]]
 name = "Donate"
 weight = 30
 identifier = "donate"
 url = "/donate/"
 [[languages.en.menu.main]]
 name = "About Us"
 weight = 40
 identifier = "about"
 url = "/about/"
 [[languages.en.menu.main]]
 name = "Internet Security Research Group (ISRG)"
 weight = 20
 identifier = "isrg"
 parent = "about"
 url = "https://www.abetterinternet.org/about/"
 [[languages.en.menu.main]]
 name = "Service Status"
 weight = 60
 identifier = "status"
 parent = "about"
 url = "https://letsencrypt.status.io/"
 [[languages.en.menu.main]]
 name = "Careers"
 weight = 80
 identifier = "careers"
 parent = "about"
 url = "https://www.abetterinternet.org/careers/"

[languages.fr]
title = "Let's Encrypt - Certificats SSL/TLS gratuits"
languageName = "Français"
contentDir = "content/fr"
languageCode= "fr-fr"
# Weight used for sorting.
weight = 20
description = """
  Let&rsquo;s&nbsp;Encrypt est une autorité de certification gratuite, automatisée et ouverte
  apporté par l'<a href="https://www.abetterinternet.org/">Internet Security Research Group (ISRG)</a>, organisme à but non lucratif.
"""
[[languages.fr.menu.main]]
 name = "Obtenir de l'aide"
 weight = 20
 url = "https://community.letsencrypt.org/c/help/aide-en-francais"
 [[languages.fr.menu.main]]
 name = "Faire un don"
 weight = 30
 identifier = "donate"
 url = "/fr/donate/"
 [[languages.fr.menu.main]]
 name = "À propos de nous"
 weight = 40
 identifier = "about"
 url = "/fr/about/"
 [[languages.fr.menu.main]]
 name = "État du service"
 weight = 60
 identifier = "status"
 parent = "about"
 url = "https://letsencrypt.status.io/"

 [languages.es]
title = "Let's Encrypt - Certificados SSL/TLS Gratuitos"
contentDir = "content/es"
languageName ="Español"
languageCode= "es-us"
# Weight used for sorting.
weight = 30
description = """
  Let&rsquo;s&nbsp;Encrypt es una autoridad de certificaci&oacute;n gratuita, automatizada, y abierta traida a ustedes por la organizaci&oacute;n sin &aacute;nimos de lucro <a href="https://www.abetterinternet.org/">Internet Security Research Group (ISRG)</a>.
"""
[[languages.es.menu.main]]
 name = "Consigue Ayuda"
 weight = 20
 url = "https://community.letsencrypt.org/"
 [[languages.es.menu.main]]
 name = "Donar"
 weight = 30
 identifier = "donate"
 url = "/donate/"
 [[languages.es.menu.main]]
 name = "Acerca De"
 weight = 40
 identifier = "about"
 url = "/about/"
  [[languages.es.menu.main]]
 name = "Internet Security Research Group (ISRG)"
 weight = 20
 identifier = "isrg"
 parent = "about"
 url = "https://www.abetterinternet.org/about/"
 [[languages.es.menu.main]]
 name = "Status de Servicio"
 weight = 60
 identifier = "status"
 parent = "about"
 url = "https://letsencrypt.status.io/"
 [[languages.es.menu.main]]
 name = "Trabajos"
 weight = 80
 identifier = "careers"
 parent = "about"
 url = "https://www.abetterinternet.org/careers/"

# Be explicit about the output formats. We only want an RSS feed for the home page.
[outputs]
home = [ "HTML", "RSS" ]
page = [ "HTML"]
section = [ "HTML"]

[outputFormats]
[outputFormats.RSS]
baseName = "feed"

# Hugo >= 0.33 is needed to get uglyURLs per section.
[uglyURLs]
  post = true

[permalinks]
  post = "/:year/:month/:day/:slug/"
