baseURL = "https://letsencrypt.org/"
languageCode= "en-us"


defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

disableKinds = ["taxonomy", "taxonomyTerm", "sitemap", "robotsTXT"]

# Note that this currently has no effect in Hugo.
timezone = "America/Los_Angeles"


[params]

# Default page top graphic if not set in page front matter. This is an integer representing the base filename.
# See the JPEG files below /static/images.
top_graphic = 5

github_username = "letsencrypt"
twitter_username = "letsencrypt"
crowdfunding_url = "https://www.generosity.com/community-fundraising/make-a-more-secure-web-with-let-s-encrypt"

# Date and time formatting, see https://gohugo.io/functions/format/
time_format_RFC3339 = "2006-01-02T15:04:05Z07:00"
time_format_RFC822 = "Mon, 02 Jan 2006 15:04:05 -0700" 
time_format_default = "Jan 2, 2006"

# Useful when translating.
enableMissingTranslationPlaceholders = true

[languages]
[languages.en]
title = "Let's Encrypt - Free SSL/TLS Certificates"
# Weight used for sorting.
weight = 1
description = """
  Let&rsquo;s&nbsp;Encrypt is a free, automated, and open certificate
  authority brought to you by the non-profit Internet Security Research Group (ISRG).
"""
[[languages.en.menu.main]]
 title = "Get Help"
 weight = 20
 url = "https://community.letsencrypt.org/"
 [[languages.en.menu.main]]
 title = "Donate"
 weight = 30
 identifier = "donate"
 url = "/donate/"
 [[languages.en.menu.main]]
 title = "About Us"
 weight = 40
 identifier = "about"
 url = "/about/"
 [[languages.en.menu.main]]
 title = "Service Status"
 weight = 60
 identifier = "status"
 parent = "about"
 url = "https://letsencrypt.status.io/"


# Be explicit about the output formats. We only want an RSS feed for the home page.
[outputs]
home = [ "HTML", "RSS" ]
page = [ "HTML"]
section = [ "HTML"]

[outputFormats]
[outputFormats.RSS]
baseName = "feed"

# Hugo >= 0.33 is needed to get uglyURLs per section.
[uglyURLs]
  post = true

[permalinks]
  post = "/:year/:month/:day/:slug/"
